name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: download snow
        run: curl -L -o snowman.7z http://derevenets.com/files/snowman-v0.1.3-win-x64.7z

      # Runs a set of commands using the runners shell
      - name: unzip snowman
        run: |
         ./7zip/7za.exe x snowman.7z

      - name: decompile mipsgcc.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipsgcc.exe > gccmips.txt
 
      - name: decompile make.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v make.exe  > make.txt

      - name: decompile mipsar.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipsar.exe > mipsar.txt

      - name: decompile mipsas.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipsas.exe > mipsar.txt

      - name: decompile mipscc1.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipscc1.exe > mipscc1.txt

      - name: decompile mipscc1.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipscc1x.exe > mipscc1x.txt

      - name: decompile mipscpp.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipscpp.exe > mipscpp.txt

      - name: decompile mipsdump.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipsdump.exe > mipsdump.txt

      - name: decompile mipsgxx.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipsgxx.exe > mipsgxx.exe

      - name: decompile mipsld.exe
        run: |
         ./snowman-v0.1.3-win-x64/nocode.exe -v mipsld.exe > mipsld.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Decompiled
          path: *txt
