# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install MSYS2 texinfo bison flex
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: |
            base-devel cmake git openssl python3 autoconf automake libtool pkg-config m4 zlib upx
            wget p7zip
          update: true
          shell: msys2 {0}

      - name: install ret decompiler
        run: |
         export PATH=$PATH:/usr/bin/
         /usr/bin/wget.exe -q https://github.com/avast/retdec/releases/download/v4.0/retdec-v4.0-windows-64b.7z
         tar -xf retdec-v4.0-windows-64b.7z

      - name: dissasemble mipsgcc.exe
        run: |
         python3 retdec/bin/retdec-decompiler.py mipsgcc.exe
         ls

