# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -L -o radare2.zip https://github.com/radareorg/radare2/releases/download/5.6.2/radare2-5.6.2-w64.zip

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         ./7zip/7za.exe x radare2.zip
         cd radare2-5.6.2-w64
         ./bin/r2pm.exe install r2ghidra

      - name: Run a multi-line script
        run: |
         cd radare2-5.6.2-w64
         ./bin/r2pm.exe install r2ghidra
         dir bin
